# Generated by Django 5.0.4 on 2024-04-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='reward',
        ),
    ]
